development:
  smtp:
    address: localhost
    port: 1025
    openssl_verify_mode: none
  database:
    username: novakj
    password: password
    name: techtools_development

test:
  smtp:
    address: localhost
    port: 1025
    openssl_verify_mode: none

production: {}
